name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change to your default branch if it's not "main"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload `client` folder
        uses: actions/upload-pages-artifact@v2
        with:
          path: client  # This is your client folder where index.html is located

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2